version : '2.2'
services:
  hello:
    build: .
    image: ascwg:securecalc
    restart: always
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://127.0.0.1:3000"]
      interval: 5s
      timeout: 10s
      retries: 3
    cpus: "1"
    mem_limit: "2048M"
